### ISSUE TITLE
release环境下更多按钮需要点击两次才会出现  并且点击2次会显示软键盘 并不会显示菜单布局

### ISSUE THREAD

**Issue by liuyaxi** [FlyJingFish/SwitchKeyboard#1]
https://github.com/user-attachments/assets/fb3fd860-0e7a-4472-9275-2a3f2cce3fce

**Comment by FlyJingFish** [comment]
添加混淆规则即可，[点此前往查看](https://github.com/FlyJingFish/SwitchKeyboard?tab=readme-ov-file#%E6%B7%B7%E6%B7%86%E8%A7%84%E5%88%99)
